# config.yaml
defaults:
  - hydra/job_logging: default
  - hydra/launcher: basic
  - hydra/sweeper: basic
  - hydra/output: default
  - env: base

hydra:
  run:
    dir: .
  job:
    chdir: False

gym_env:
  id: "Acrobot-v1" # Gym环境ID
  env_config: {} # Gym环境的其他配置


ppo_params:
  policy: "MlpPolicy" # 使用的策略
  gamma: 0.99
  n_steps: 2048
  ent_coef: 0.0
  learning_rate: 0.0003
  vf_coef: 0.5
  max_grad_norm: 0.5
  batch_size: 64
  n_epochs: 10  
  clip_range: 0.2
  verbose: 1
  device: "cuda"
  tensorboard_log: "./models"

train:
  env_name: 'Acrobot-v1' # 环境名
  total_timesteps: 1000000 # 训练的总步数
  save_dir: "./models" # 模型保存路径
  deterministic: False # 是否确定性
  train_mode: True # 是否训练
  model_num: 5 # 模型数量
  load_dir: "./models" # 模型加载路径
  num_eval_episodes: 10 # 测试的轮数
  collect_episodes: 50 # episode的轮数
  collect_steps: 2000
  render: False # 是否渲染
  cuda: "cuda:0" # 训练的设备

detect:
  render: False # 是否渲染
  detector_type: 'riqn' # 检测器类型
  env_name: 'Acrobot-v1'
  param_name: 'LINK_MASS_2' # 选择的参数名
  n_samples: 1000 # number of sumples to reconstruct data distribution
  collect_trajs: 10 # number of trajectories to test
