# config.yaml
defaults:
  - _self_
  - env: base
  - override hydra/job_logging: default
  - override hydra/launcher: basic
  - override hydra/output: default
  - override hydra/sweeper: basic

hydra:
  run:
    dir: .
  job:
    chdir: False

env:
  name: "gridworld" # Gym环境ID
  env_config: {} # Gym环境的其他配置

train:
  total_timesteps: 100000 # 训练的总步数
  save_dir: "save/model/forward_model" # 模型保存路径
  deterministic: False # 是否确定性
  train_mode: False # 是否训练
  model_num: 5 # 模型数量
  load_dir: 'save/model/policy' # 模型加载路径
  num_eval_episodes: 10 # 测试的轮数
  collect_episodes: 20 # episode的轮数
  collect_steps: 2500
  policy_id: 0
  map_id: 0
  render: True # 是否渲染
  cuda: "cuda:0" # 训练的设备

detect:
  render: True # 是否渲染
  n_trials: 10
  n_maps: 10
  policy_id: 0 # 选择的策略ID
  default_prob: 0.1
  test_id: 6 # 测试的id
  param_name: 'LINK_LENGTH_2' # 选择的参数名
  collect_trajs: 20 # 采样的轮数
  value_iterations: 500
  save_dir: 'save/detect' # 保存路径
